name: Mirror to vasilache06/mirror-2

on:
  push:
    branches: ["**"]
    tags: ["**"]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

concurrency:
  group: mirror
  cancel-in-progress: false

jobs:
  mirror:
    if: github.repository != 'vasilache06/mirror-2' && github.repository != 'vasilache06/mirror'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: https://github.com/vasilache06/mirror-2.git
          GIT_USERNAME: vasilache06
          GIT_PASSWORD: ${{ secrets.MIRROR_TOKEN }}
          PUSH_ALL_REFS: true
          GIT_PUSH_ARGS: --tags --force --prune
